version: '3'
services:
  client:
    image: mern-client
    ports:
      - "80:80"
    depends_on:
      - server
  server:
    image: mern-server
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - app-network
    environment:
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=27017
      - MONGO_DB=myapp_db
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - my-data:/data/db
    networks:
      - app-network

volumes:
  my-data: 

networks:
    app-network: