version: '3'
services:
  web:
    image: mern-test
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - app-network
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - my-data:/data/db
    networks:
      - app-network

volumes:
  my-data: 

networks:
    app-network: